import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "@/redux/provider";
import Header from "@/components/Header/Header";

const poppins = Poppins({ weight: ["400"], subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Posts app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={poppins.className}>
          <Header />
          <main className="container">{children}</main>
        </body>
      </Providers>
    </html>
  );
}
